s/\bAc_Legacy_Controller_Exception\b/Ac_Controller_Exception/g
s/\bAc_Legacy_Controller_Response\b/Ac_Controller_Response/g
s/\bAc_Legacy_Controller_Response_Json\b/Ac_Controller_Response_Json/g
s/\bAc_Legacy_Controller_Response_JsonPart\b/Ac_Controller_Response_JsonPart/g
s/\bAc_Legacy_Controller_Response_Global\b/Ac_Controller_Response_Global/g
s/\bAc_Legacy_Controller_Response_Html\b/Ac_Controller_Response_Html/g
s/\bAc_Legacy_Controller_Response_Http\b/Ac_Controller_Response_Http/g
s/\bAc_Legacy_Controller_Response_Part\b/Ac_Controller_Response_Part/g
s/\bAc_Legacy_Controller_Context_Http\b/Ac_Controller_Context_Http/g
s/\bAc_Legacy_Controller_Context\b/Ac_Controller_Context/g
s/\bAc_Legacy_Output_Joomla3\b/Ac_Controller_Output_Joomla3/g
s/\bAc_Legacy_Output_Debug\b/Ac_Controller_Output_Debug/g
s/\bAc_Legacy_Output_Joomla\b/Ac_Controller_Output_Joomla/g
s/\bAc_Legacy_Output_Native\b/Ac_Controller_Output_Native/g
s/\bAc_Legacy_Output_Joomla15\b/Ac_Controller_Output_Joomla15/g
s/\bAc_Legacy_Controller\b/Ac_Controller/g
s/\bAc_Legacy_Output\b/Ac_Output/g
s/\bAc_Legacy_Template_Helper_Html\b/Ac_Template_Helper_Html/g
s/\bAc_Legacy_Template_HtmlPage\b/Ac_Template_HtmlPage/g
s/\bAc_Legacy_Template_Html\b/Ac_Template_Html/g
s/\bAc_Legacy_Template_JoomlaPage\b/Ac_Template_JoomlaPage/g
s/\bAc_Legacy_Template_Helper\b/Ac_Template_Helper/g
s/\bAc_Legacy_Template\b/Ac_Template/g
s#\bobsolete/Ac/Legacy/Controller/Exception\.php\b#classes/Ac/Controller/Exception.php#g
s#\bobsolete/Ac/Legacy/Controller/Response\.php\b#classes/Ac/Controller/Response.php#g
s#\bobsolete/Ac/Legacy/Controller/Response/Json\.php\b#classes/Ac/Controller/Response/Json.php#g
s#\bobsolete/Ac/Legacy/Controller/Response/JsonPart\.php\b#classes/Ac/Controller/Response/JsonPart.php#g
s#\bobsolete/Ac/Legacy/Controller/Response/Global\.php\b#classes/Ac/Controller/Response/Global.php#g
s#\bobsolete/Ac/Legacy/Controller/Response/Html\.php\b#classes/Ac/Controller/Response/Html.php#g
s#\bobsolete/Ac/Legacy/Controller/Response/Http\.php\b#classes/Ac/Controller/Response/Http.php#g
s#\bobsolete/Ac/Legacy/Controller/Response/Part\.php\b#classes/Ac/Controller/Response/Part.php#g
s#\bobsolete/Ac/Legacy/Controller/Context/Http\.php\b#classes/Ac/Controller/Context/Http.php#g
s#\bobsolete/Ac/Legacy/Controller/Context\.php\b#classes/Ac/Controller/Context.php#g
s#\bobsolete/Ac/Legacy/Output/Joomla3\.php\b#classes/Ac/Controller/Output/Joomla3.php#g
s#\bobsolete/Ac/Legacy/Output/Debug\.php\b#classes/Ac/Controller/Output/Debug.php#g
s#\bobsolete/Ac/Legacy/Output/Joomla\.php\b#classes/Ac/Controller/Output/Joomla.php#g
s#\bobsolete/Ac/Legacy/Output/Native\.php\b#classes/Ac/Controller/Output/Native.php#g
s#\bobsolete/Ac/Legacy/Output/Joomla15\.php\b#classes/Ac/Controller/Output/Joomla15.php#g
s#\bobsolete/Ac/Legacy/Controller\.php\b#classes/Ac/Controller.php#g
s#\bobsolete/Ac/Legacy/Output\.php\b#classes/Ac/Output.php#g
s#\bobsolete/Ac/Legacy/Template/Helper/Html\.php\b#classes/Ac/Template/Helper/Html.php#g
s#\bobsolete/Ac/Legacy/Template/HtmlPage\.php\b#classes/Ac/Template/HtmlPage.php#g
s#\bobsolete/Ac/Legacy/Template/Html\.php\b#classes/Ac/Template/Html.php#g
s#\bobsolete/Ac/Legacy/Template/JoomlaPage\.php\b#classes/Ac/Template/JoomlaPage.php#g
s#\bobsolete/Ac/Legacy/Template/Helper\.php\b#classes/Ac/Template/Helper.php#g
s#\bobsolete/Ac/Legacy/Template\.php\b#classes/Ac/Template.php#g
